apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: gitops-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE_TAG
      type: string
      default: "latest"
  workspaces:
    - name: shared-workspace
  tasks:
    - name: maven-build
      taskRef:
        name: maven-build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)

    - name: sonarqube-scan
      taskRef:
        name: sonarqube-scan
      runAfter:
        - maven-build
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: docker-build-push
      taskRef:
        name: docker-build-push
      runAfter:
        - sonarqube-scan
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)

    - name: deploy-dev
      taskRef:
        name: deploy-to-env
      runAfter:
        - docker-build-push
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: ENVIRONMENT
          value: "dev"

    - name: manual-approval
      taskRef:
        name: manual-approval
      runAfter:
        - deploy-dev
      params:
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: TIMEOUT
          value: "600"

    - name: deploy-prod
      taskRef:
        name: deploy-to-env
      runAfter:
        - manual-approval
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: ENVIRONMENT
          value: "prod"
